"""
Golden parity tests: verify our mcrypt wrapper matches PHP mcrypt_decrypt() byte-for-byte.

Test vectors are generated by scripts/mcrypt_test_vectors.php and stored in
scripts/mcrypt_test_vectors.json. Each vector contains a ciphertext produced by
PHP's mcrypt_encrypt(); we decrypt with our ctypes wrapper and verify we recover
the original plaintext exactly.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from stages.mcrypt_wrapper import McryptHandleCache, mcrypt_decrypt

VECTORS_PATH = Path(__file__).parent / "scripts" / "mcrypt_test_vectors.json"


def load_vectors() -> list[dict]:
    with open(VECTORS_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def handle_cache() -> McryptHandleCache:
    cache = McryptHandleCache()
    yield cache
    cache.close_all()


VECTORS = load_vectors()


@pytest.mark.parametrize(
    "vector",
    VECTORS,
    ids=[v["label"] for v in VECTORS],
)
def test_mcrypt_parity(vector: dict, handle_cache: McryptHandleCache) -> None:
    """Decrypt PHP-generated ciphertext and verify plaintext matches exactly."""
    algo = vector["algo"]
    mode = vector["mode"]
    key = bytes.fromhex(vector["key_hex"])
    iv = bytes.fromhex(vector["iv_hex"]) if vector["iv_hex"] else None
    ciphertext = bytes.fromhex(vector["ciphertext_hex"])
    expected_plaintext = bytes.fromhex(vector["plaintext_hex"])

    result = mcrypt_decrypt(algo, mode, key, iv, ciphertext, handle_cache=handle_cache)

    assert result is not None, f"mcrypt_decrypt returned None for {vector['label']}"

    # PHP mcrypt_encrypt zero-pads plaintext to block size, so the decrypted
    # result may be longer than the original plaintext. We compare the prefix
    # matching the original plaintext length, and verify any trailing bytes are nulls.
    assert result[: len(expected_plaintext)] == expected_plaintext, (
        f"Plaintext mismatch for {vector['label']}:\n"
        f"  expected: {expected_plaintext.hex()}\n"
        f"  got:      {result[: len(expected_plaintext)].hex()}"
    )

    # Trailing bytes (if any) should be null padding from block alignment
    trailing = result[len(expected_plaintext) :]
    if trailing:
        assert trailing == b"\x00" * len(trailing), (
            f"Non-null trailing bytes for {vector['label']}: {trailing.hex()}"
        )
